### ISSUE TITLE
Rename `placeholder` prop to `isVisible`

### ISSUE THREAD

**Issue by scottdj92** [peterlazzarino/react-evergage-AB#13]
The `placeholder` prop is unclear. Placeholders have the connotation of a temporary field that's within an input. This is a dissonance from the actual functionality, which adds a visibility: hidden field to the component.

**Comment by peterlazzarino** [comment]
The intent is to provide a placeholder only until an experience is chosen so I don't think isVisible really fits either since it will become visible when an experience is chosen or the control is used as a fallback. 

What about something like initWithPlaceholder?

**Comment by scottdj92** [comment]
So it defaults to a hidden experience unless we specify an experience?

**Comment by peterlazzarino** [comment]
a little background might help. When using evergage, they will choose an experience for a campaign or have the user be in the control group but that decision could take n milliseconds after page load, usually < 50. The problem that can present is that for above the fold components, we need to make a decision about what to show before that decision is made by evergage, the third party. 

To work around this we can either 

1. Show nothing - Andrew's initial commit did this which collapsed the container dom node, resulting in a weird experience with the element shifting shape after the experience is chosen.
2. Show the control group - Also a weird experience because if you are no in the control you will see the element change to something else.
3. The placeholder solution, show the control but as a visible hidden element to prop up the dom in anticipation of an experience or control being chosen. Its not perfect and only works well when the control and experience are approximately the same size but it makes the transition much less jarring.

**Comment by scottdj92** [comment]
Hmm, that makes sense. Why not rename it to something like `isControlGroup`

**Comment by peterlazzarino** [comment]
well because the reason we have the placeholder is because at that point we are not sure which group they are going to be in. Because evergage holds the users state and information about which experience group they are in, a user could be doing a hard reload only to end up on the same experience they saw last page view. 

isControlGroup would be misleading since the placeholder could just as easily be used to block the decision making duration leading to an experience being mounted vs the control.

**Comment by scottdj92** [comment]
If Evergage holds the user state and info, and a single user is in the same group; wouldn't them hard reloading the page lead into the same experience regardless?

There's definitely a conceptual collision between Evergage logic and the English language here 😛

**Comment by peterlazzarino** [comment]
haha true. I just mean that an isControlGroup props naming could be confusing if the end result isnt always covering up a dom element with the intent of mounting a control group.
